---
title: " Sydney Informatics Hub Training Code of Conduct"
---


The [Sydney Informatics Hub (SIH)](https://informatics.sydney.edu.au/) is a Core Research Facility of the University of Sydney. SIH provides support, training, and expertise on research data, analyses and computing for research staff, students and affiliates of the University. We deliver policies, systems, advice, engineering and training to research staff, students and affiliates of the University.

We are committed to creating a friendly and respectful place for learning, teaching and contributing to our training materials. All participants in our events and communications are expected to show respect and courtesy to others.

To make clear what is expected, everyone participating in our activities is required to conform to the Code of Conduct. This Code of Conduct applies to all spaces managed by SIH including, but not limited to, workshops, email lists, and online forums such as GitHub, Slack and Twitter. Workshop hosts are expected to assist with the enforcement of the Code of Conduct.


***

## The Training Code of Conduct

We are dedicated to providing a welcoming and supportive learning environment for all people, regardless of background or identity. As such, we do not tolerate behaviour that is disrespectful to our teachers or learners or that excludes, intimidates, or causes discomfort to others. We do not tolerate discrimination or harassment based on characteristics that include, but are not limited to, gender identity and expression, sexual orientation, disability, physical appearance, body size, citizenship, nationality, ethnic or social origin, pregnancy, familial status, veteran status, genetic information, religion or belief (or lack thereof), membership of a national minority, property, age, education, socio-economic status, technical choices, and experience level.

Everyone who participates in our activities is required to conform to this Code of Conduct. It applies to all spaces managed by SIH including, but not limited to, workshops, email lists, and online forums such as GitHub, Slack and Twitter. Workshop hosts are expected to assist with the enforcement of the Code of Conduct. By participating, participants indicate their acceptance of the procedures by which SIH resolves any Code of Conduct incidents, which may include storage and processing of their personal information.

### Expected Behavior

All participants in our events and communications are expected to show respect and courtesy to others. All interactions should be professional regardless of platform: either online or in-person. In order to foster a positive and professional learning environment we encourage the following kinds of behaviours in all SIH events and platforms:

- Use welcoming and inclusive language
- Be respectful of different viewpoints and experiences
- Gracefully accept constructive criticism
- Focus on what is best for the community
- Show courtesy and respect towards other community members


### Unacceptable Behavior

Examples of unacceptable behavior by participants include:

- sustained disruption of talks, events or communications
- written or verbal comments which have the effect of excluding people on the basis of membership of any specific group
- causing someone to fear for their safety, such as through stalking, following, or intimidation
- violent threats or language directed against another person
- the display of sexual or violent images
- unwelcome sexual attention
- nonconsensual or unwelcome physical contact
- insults or put downs
- sexist, racist, homophobic, transphobic, ableist, or exclusionary jokes
- excessive swearing
- incitement to violence, suicide, or self-harm
- continuing to initiate interaction (including photography or recording) with someone after being asked to stop
- publication of private communication without consent

### Consequences of Unacceptable Behavior

1. Participants who are asked to stop any inappropriate behavior are expected to comply immediately. This applies to any of our events and platforms, either online or in-person.

2. Participants may be asked to relocate to another seat, if possible, within the classroom.

3. If a participant engages in behavior that violates this code of conduct, the organizers may warn the offender, ask them to leave the event or platform (without refund), and/or [formally appeal](#reporting) to the University of Sydney to investigate the Code of Conduct violation and impose appropriate sanctions. 

***

## Incident Reporting Guidelines {#reporting}
### Contact points, and initial reporting guidelines

If someone violates the [Code of Conduct](index.html) during one of our events we ask that you report it to the trainer, event host or organiser. You can also send a report to SIH training about the incident by emailing [sih.training@sydney.edu.au](mailto:sih.training@sydney.edu.au). If a violation occurs in an online space outside of organised events, please email [sih.training@sydney.edu.au](mailto:sih.training@sydney.edu.au) about the incident. Our trainers will then work with you to determine whether a formal report to the University is necessary and prepare this report, as well as the correct process to follow.

### Relevant University of Sydney policies and procedures

The University of Sydney has several policies and procedures which we have used as the basis for our Code of Conduct. All attendees of our workshops are expected to follow these policies and procedures: 

- Students are bound by the [Student Code of Conduct](http://sydney.edu.au/policies/showdoc.aspx?recnum=PDOC2011/215&RendNum=0) of which section 4 outlines personal conduct. 
- Staff and affiliates are bound by the [Staff Code of Conduct](http://sydney.edu.au/policies/showdoc.aspx?recnum=PDOC2011/65&RendNum=0). 
- **Both** staff and students are required to abide by the [Bullying, harassment and discrimination prevention policy](http://sydney.edu.au/policies/showdoc.aspx?recnum=PDOC2011/168&RendNum=0). 

Staff matters are handled by University of Sydney Human Resources and student matters are handled by the Registrar. There may be circumstances which warrant both HR and Registrar involvement depending on the incident/matter.

### Formal reporting guidelines
    
**Please ask the SIH trainer to assist you if you'd like to report an incident!**
    
Student misconduct should be reported to the [Registrar]( https://sydney.edu.au/students/student-misconduct/report-student-misconduct.html). Staff misconduct should be reported by following the guidelines [here](https://intranet.sydney.edu.au/employment/support/bullying_prevention/framing-written-allegation.html) using [Riskware](https://riskware.sydney.edu.au/) to submit the incident report. Alternatively, in line with [this policy](http://sydney.edu.au/policies/showdoc.aspx?recnum=PDOC2015/406&RendNum=0), a report can be made to [Workplace Relations](https://intranet.sydney.edu.au/employment/support/bullying_prevention.html).

***

### Note
This Code of Conduct is based on the [Carpentries](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html), and is a reframing of the University of Sydney's Code of Conduct policies for staff and students. If you'd like to suggest improvements please let us know at [sih.training@sydney.edu.au](mailto:sih.training@sydney.edu.au).